using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace MVVM_Essentials_Lib
{
    public class CreateRandomNumber
    {
        public static string IsAutoGenerated(int Length)
        {
            Random rn = new Random();
            string charsToUse = "ABCDEFGHIJKLMNOPQRTUVWXYZ1234567890";

            MatchEvaluator RandomChar = delegate (Match m)
            {
                return charsToUse[rn.Next(charsToUse.Length)].ToString();
            };
            var messageID = Regex.Replace("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "X", RandomChar);
            return messageID.Substring(0, Length).ToUpper();
        }
    }
}
